import "server-only";
import fs from "fs";
import path from "path";
import { db } from "@/db";
import { servers, consoleLines, serverPlayers } from "@/db/schema";
import { eq } from "drizzle-orm";
import type { MinecraftServerProvider, ProvisionInput } from "@/lib/minecraft/provider";
import { softwareMeta } from "@/lib/minecraft/catalog";

export const STORAGE_ROOT = process.env.STORAGE_PATH
  ? path.resolve(process.env.STORAGE_PATH)
  : path.resolve(process.cwd(), "data", "servers");

export const BACKUP_ROOT = path.resolve(STORAGE_ROOT, "..", "backups");

export function serverDataDir(serverId: string): string {
  return path.join(STORAGE_ROOT, serverId);
}

/**
 * Resolves `relPath` against `baseDir` and guarantees the resolved path
 * stays inside `baseDir`. Throws if the request attempts to traverse
 * outside of the server's sandboxed directory (PRD section 13/44).
 */
export function safeResolve(baseDir: string, relPath: string): string {
  const normalized = path.normalize(relPath ?? "").replace(/^([./\\]+)/, "");
  const resolved = path.resolve(baseDir, normalized);
  const baseWithSep = baseDir.endsWith(path.sep) ? baseDir : baseDir + path.sep;
  if (resolved !== baseDir && !resolved.startsWith(baseWithSep)) {
    throw new Error("Path escapes the server's sandbox directory.");
  }
  return resolved;
}

export function defaultProperties(input: { mcVersion: string; motd: string; maxPlayers: number; port: number; levelName: string }) {
  return {
    "server-port": String(input.port),
    "level-name": input.levelName,
    motd: input.motd,
    gamemode: "survival",
    difficulty: "easy",
    "max-players": String(input.maxPlayers),
    "online-mode": "true",
    pvp: "true",
    "allow-flight": "false",
    "allow-nether": "true",
    "spawn-protection": "16",
    "view-distance": "10",
    "simulation-distance": "10",
    "enable-command-block": "false",
    "white-list": "false",
    hardcore: "false",
  } as Record<string, string>;
}

export function serializeProperties(props: Record<string, string>): string {
  const lines = ["#Minecraft server properties", `#Generated by Peakcraft Panel on ${new Date().toISOString()}`];
  for (const [key, value] of Object.entries(props)) {
    lines.push(`${key}=${value}`);
  }
  return lines.join("\n") + "\n";
}

export function parseProperties(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const idx = line.indexOf("=");
    if (idx === -1) continue;
    result[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return result;
}

async function appendConsole(serverId: string, line: string, stream: "OUT" | "IN" | "SYSTEM" = "OUT") {
  await db.insert(consoleLines).values({ serverId, line, stream });
}

async function setState(serverId: string, state: (typeof servers.$inferSelect)["state"], extra: Record<string, unknown> = {}) {
  await db.update(servers).set({ state, stateChangedAt: new Date(), updatedAt: new Date(), ...extra }).where(eq(servers.id, serverId));
}

/**
 * DevelopmentMockProvider — a self-contained provider that performs real
 * filesystem provisioning (so the file manager, properties editor, worlds
 * and backups are all fully functional) while simulating the Minecraft
 * process lifecycle instead of spawning a real Docker container. This keeps
 * the application fully demoable in any sandbox without Docker access,
 * while implementing the exact same interface a LocalDockerProvider or
 * FutureCloudProvider would implement.
 */
export class DevelopmentMockProvider implements MinecraftServerProvider {
  async provision(input: ProvisionInput): Promise<{ dataDir: string }> {
    const dataDir = serverDataDir(input.serverId);
    fs.mkdirSync(dataDir, { recursive: true });
    fs.mkdirSync(path.join(dataDir, "world"), { recursive: true });
    fs.mkdirSync(path.join(dataDir, "world", "region"), { recursive: true });
    fs.mkdirSync(path.join(dataDir, "logs"), { recursive: true });
    fs.mkdirSync(path.join(dataDir, "plugins"), { recursive: true });
    fs.mkdirSync(path.join(dataDir, "mods"), { recursive: true });

    fs.writeFileSync(path.join(dataDir, "eula.txt"), `#By changing the setting below to TRUE you are indicating your agreement to the Minecraft EULA.\n#Accepted programmatically via Peakcraft Panel.\neula=true\n`);
    fs.writeFileSync(path.join(dataDir, "whitelist.json"), "[]\n");
    fs.writeFileSync(path.join(dataDir, "ops.json"), "[]\n");
    fs.writeFileSync(path.join(dataDir, "banned-players.json"), "[]\n");
    fs.writeFileSync(path.join(dataDir, "banned-ips.json"), "[]\n");
    fs.writeFileSync(
      path.join(dataDir, "world", "level.dat.txt"),
      `This is a placeholder for the ${input.mcVersion} world save data managed by the ${input.name} server.\n`,
    );
    fs.writeFileSync(path.join(dataDir, "logs", "latest.log"), `[${new Date().toISOString()}] [Server thread/INFO]: Provisioning ${input.name}\n`);

    const meta = softwareMeta(input.software);
    fs.writeFileSync(
      path.join(dataDir, "README.txt"),
      `Server: ${input.name}\nSoftware: ${meta.label}\nVersion: ${input.mcVersion}\n\nThis data directory is fully sandboxed and safe to browse through the File Manager.\n`,
    );

    return { dataDir };
  }

  async start(serverId: string): Promise<void> {
    const [server] = await db.select().from(servers).where(eq(servers.id, serverId)).limit(1);
    if (!server) throw new Error("Server not found");
    if (server.state !== "STOPPED" && server.state !== "ERROR") {
      throw new Error(`Cannot start a server in state ${server.state}`);
    }
    await setState(serverId, "STARTING", { lastStartedAt: new Date() });
    await appendConsole(serverId, `Starting ${softwareMeta(server.software).label} server version ${server.mcVersion}...`, "SYSTEM");
  }

  async stop(serverId: string): Promise<void> {
    const [server] = await db.select().from(servers).where(eq(servers.id, serverId)).limit(1);
    if (!server) throw new Error("Server not found");
    if (server.state !== "RUNNING" && server.state !== "STARTING") {
      throw new Error(`Cannot stop a server in state ${server.state}`);
    }
    await setState(serverId, "STOPPING");
    await appendConsole(serverId, "Stopping the server...", "SYSTEM");
    await db.update(serverPlayers).set({ online: false }).where(eq(serverPlayers.serverId, serverId));
  }

  async restart(serverId: string): Promise<void> {
    const [server] = await db.select().from(servers).where(eq(servers.id, serverId)).limit(1);
    if (!server) throw new Error("Server not found");
    if (server.state !== "RUNNING") {
      throw new Error(`Cannot restart a server in state ${server.state}`);
    }
    await setState(serverId, "RESTARTING");
    await appendConsole(serverId, "Restarting the server...", "SYSTEM");
    await db.update(serverPlayers).set({ online: false }).where(eq(serverPlayers.serverId, serverId));
  }

  async kill(serverId: string): Promise<void> {
    const [server] = await db.select().from(servers).where(eq(servers.id, serverId)).limit(1);
    if (!server) throw new Error("Server not found");
    if (server.state === "STOPPED") return;
    await setState(serverId, "STOPPED");
    await appendConsole(serverId, "Process killed by user request.", "SYSTEM");
    await db.update(serverPlayers).set({ online: false }).where(eq(serverPlayers.serverId, serverId));
  }

  async destroy(serverId: string): Promise<void> {
    const dataDir = serverDataDir(serverId);
    await fs.promises.rm(dataDir, { recursive: true, force: true });
    const backupsDir = path.join(BACKUP_ROOT, serverId);
    await fs.promises.rm(backupsDir, { recursive: true, force: true });
  }

  async sendCommand(serverId: string, command: string): Promise<void> {
    const { applyConsoleCommand } = await import("@/lib/minecraft/commands");
    await applyConsoleCommand(serverId, command);
  }
}
